//! Catálogo de textos: `(clave, español, inglés, sueco)`. Los marcadores `{0}`, `{1}`… se sustituyen con `tf()`.
//! Un test (en `tests.rs`) comprueba que cada clave usada en el código existe aquí y que las tres lenguas
//! tienen texto y los mismos marcadores. Los datos que vienen de Bolagsverket no se traducen.

pub type Entry = (&'static str, &'static str, &'static str, &'static str);

pub const ENTRIES: &[Entry] = &[
    // ───── Pruebas ─────
    ("test.hello", "Hola {0}, tienes {1}", "Hello {0}, you have {1}", "Hej {0}, du har {1}"),

    // ───── Aplicación y elementos comunes ─────
    ("app.description", "Inteligencia financiera de empresas suecas: datos del registro, cifras y comparación con el sector.", "Financial intelligence on Swedish companies: register data, key figures and sector comparison.", "Finansiell information om svenska företag: registeruppgifter, nyckeltal och branschjämförelse."),
    ("ui.account_menu", "Menú de cuenta de {0}", "Account menu for {0}", "Kontomeny för {0}"),
    ("ui.brand_label", "Siffra, ir al inicio", "Siffra, go to start", "Siffra, till startsidan"),
    ("ui.copied", "Copiado", "Copied", "Kopierat"),
    ("ui.copy_failed", "No se pudo copiar", "Could not copy", "Kunde inte kopiera"),
    ("ui.dark_mode", "Modo oscuro", "Dark mode", "Mörkt läge"),
    ("ui.language", "Idioma", "Language", "Språk"),
    ("ui.main_menu", "Menú principal", "Main menu", "Huvudmeny"),
    ("ui.skip", "Saltar al contenido", "Skip to content", "Hoppa till innehållet"),
    ("ui.theme_tip", "Cambiar entre tema claro y oscuro", "Switch between light and dark theme", "Växla mellan ljust och mörkt tema"),
    ("common.cancel", "Cancelar", "Cancel", "Avbryt"),
    ("common.save", "Guardar", "Save", "Spara"),
    ("common.example", "Ejemplo", "Example", "Exempel"),
    ("common.example_upper", "EJEMPLO", "EXAMPLE", "EXEMPEL"),
    ("common.example_tip", "Datos ficticios de demostración: no pertenecen a una empresa real.", "Fictitious demo data: it does not belong to a real company.", "Fiktiva demodata: de tillhör inte något verkligt företag."),
    ("unit.tkr", "mil SEK", "kSEK", "tkr"),
    ("unit.mkr", "M SEK", "MSEK", "mkr"),
    ("unit.sek", "SEK", "SEK", "kr"),

    // ───── Navegación ─────
    ("nav.group.companies", "Empresas", "Companies", "Företag"),
    ("nav.group.business", "Tu negocio", "Your business", "Din verksamhet"),
    ("nav.group.admin", "Administración", "Administration", "Administration"),
    ("nav.search", "Buscar empresas", "Search companies", "Sök företag"),
    ("nav.search.short", "Buscar", "Search", "Sök"),
    ("nav.watch", "Vigilancia de empresas", "Company watch", "Bevakning"),
    ("nav.watch.short", "Alertas", "Alerts", "Bevakning"),
    ("nav.liquidity", "Previsión de liquidez", "Liquidity forecast", "Likviditetsprognos"),
    ("nav.liquidity.short", "Liquidez", "Liquidity", "Likviditet"),
    ("nav.sie", "Importar contabilidad (SIE)", "Import accounts (SIE)", "Importera bokföring (SIE)"),
    ("nav.sie.short", "SIE", "SIE", "SIE"),
    ("nav.invoices", "Facturas", "Invoices", "Fakturor"),
    ("nav.invoices.short", "Facturas", "Invoices", "Fakturor"),
    ("nav.users", "Usuarios", "Users", "Användare"),
    ("nav.activity", "Actividad", "Activity", "Aktivitet"),
    ("nav.profile", "Mi perfil", "My profile", "Min profil"),
    ("nav.logout", "Cerrar sesión", "Sign out", "Logga ut"),
    ("nav.new", "nuevo", "new", "ny"),

    // ───── Errores y páginas de mensaje ─────
    ("err.csrf_title", "Solicitud no válida", "Invalid request", "Ogiltig begäran"),
    ("err.csrf", "El formulario caducó o no es válido. Vuelve atrás, recarga la página e inténtalo de nuevo.", "The form expired or is not valid. Go back, reload the page and try again.", "Formuläret har gått ut eller är ogiltigt. Gå tillbaka, ladda om sidan och försök igen."),
    ("err.forbidden_title", "Sin permiso", "No permission", "Saknar behörighet"),
    ("err.forbidden", "Tu rol no permite esta acción.", "Your role does not allow this action.", "Din roll tillåter inte den här åtgärden."),
    ("err.generic_title", "Algo salió mal", "Something went wrong", "Något gick fel"),
    ("err.generic", "No se pudo completar la operación. Inténtalo de nuevo.", "The operation could not be completed. Please try again.", "Åtgärden kunde inte slutföras. Försök igen."),
    ("nf.page.title", "Página no encontrada", "Page not found", "Sidan hittades inte"),
    ("nf.page.text", "La página que buscas no existe.", "The page you are looking for does not exist.", "Sidan du söker finns inte."),
    ("nf.company.title", "Empresa no encontrada", "Company not found", "Företaget hittades inte"),
    ("nf.company.text", "No encontramos esa empresa. Revisa el número de organización (10 dígitos).", "We could not find that company. Check the organisation number (10 digits).", "Vi hittade inte företaget. Kontrollera organisationsnumret (10 siffror)."),
    ("nf.to_search", "Ir a la búsqueda", "Go to search", "Till sökningen"),

    // ───── Acceso ─────
    ("auth.login", "Iniciar sesión", "Sign in", "Logga in"),
    ("auth.welcome", "Bienvenido a Siffra", "Welcome to Siffra", "Välkommen till Siffra"),
    ("auth.subtitle", "Inteligencia financiera de empresas suecas.", "Financial intelligence on Swedish companies.", "Finansiell information om svenska företag."),
    ("auth.identifier", "Correo o nombre de usuario", "Email or username", "E-post eller användarnamn"),
    ("auth.password", "Contraseña", "Password", "Lösenord"),
    ("auth.submit", "Entrar", "Sign in", "Logga in"),
    ("auth.no_account", "¿No tienes cuenta? Pídela a un administrador.", "No account? Ask an administrator for one.", "Inget konto? Be en administratör skapa ett."),
    ("auth.err.invalid", "Usuario o contraseña incorrectos.", "Wrong username or password.", "Fel användarnamn eller lösenord."),
    ("auth.err.blocked", "Demasiados intentos fallidos. Espera 15 minutos e inténtalo de nuevo.", "Too many failed attempts. Wait 15 minutes and try again.", "För många misslyckade försök. Vänta 15 minuter och försök igen."),
    ("auth.err.csrf", "La página caducó. Inténtalo de nuevo.", "The page expired. Please try again.", "Sidan har gått ut. Försök igen."),

    // ───── Perfil ─────
    ("prof.title", "Mi perfil", "My profile", "Min profil"),
    ("prof.data", "Mis datos", "My details", "Mina uppgifter"),
    ("prof.saved", "Perfil guardado.", "Profile saved.", "Profilen har sparats."),
    ("prof.password", "Contraseña", "Password", "Lösenord"),
    ("prof.current_password", "Contraseña actual", "Current password", "Nuvarande lösenord"),
    ("prof.new_password", "Contraseña nueva", "New password", "Nytt lösenord"),
    ("prof.repeat_password", "Repite la contraseña nueva", "Repeat the new password", "Upprepa det nya lösenordet"),
    ("prof.change_password", "Cambiar contraseña", "Change password", "Byt lösenord"),
    ("prof.force_change", "Tu contraseña es temporal. Cámbiala para continuar.", "Your password is temporary. Change it to continue.", "Ditt lösenord är tillfälligt. Byt det för att fortsätta."),
    ("prof.err.current", "La contraseña actual no es correcta.", "The current password is not correct.", "Nuvarande lösenord är fel."),
    ("prof.err.mismatch", "Las contraseñas nuevas no coinciden.", "The new passwords do not match.", "De nya lösenorden stämmer inte överens."),
    ("prof.err.same", "La contraseña nueva debe ser distinta de la actual.", "The new password must differ from the current one.", "Det nya lösenordet måste skilja sig från det nuvarande."),
    ("pw.hint", "Mínimo {0} caracteres. Una frase larga es lo mejor.", "At least {0} characters. A long phrase works best.", "Minst {0} tecken. En lång mening fungerar bäst."),
    ("pw.too_short", "La contraseña es demasiado corta.", "The password is too short.", "Lösenordet är för kort."),
    ("pw.too_simple", "La contraseña es demasiado simple: mezcla letras, números y símbolos.", "The password is too simple: mix letters, numbers and symbols.", "Lösenordet är för enkelt: blanda bokstäver, siffror och symboler."),

    // ───── Roles ─────
    ("role.superadmin", "Superadmin", "Superadmin", "Superadmin"),
    ("role.admin", "Admin", "Admin", "Admin"),
    ("role.user", "Usuario", "User", "Användare"),

    // ───── Usuarios (CRUD) ─────
    ("usr.lead.super", "Crea y gestiona todas las cuentas: usuarios, admins y superadmins.", "Create and manage all accounts: users, admins and superadmins.", "Skapa och hantera alla konton: användare, administratörer och superadmin."),
    ("usr.lead.admin", "Crea y gestiona las cuentas de los usuarios de la plataforma.", "Create and manage the platform's user accounts.", "Skapa och hantera plattformens användarkonton."),
    ("usr.admin_note", "Como admin solo puedes gestionar cuentas con rol Usuario.", "As an admin you can only manage accounts with the User role.", "Som admin kan du bara hantera konton med rollen Användare."),
    ("usr.new", "Nuevo usuario", "New user", "Ny användare"),
    ("usr.search", "Buscar por nombre o correo…", "Search by name or email…", "Sök på namn eller e-post…"),
    ("usr.all_roles", "Todos los roles", "All roles", "Alla roller"),
    ("usr.filter", "Filtrar", "Filter", "Filtrera"),
    ("usr.count.one", "{0} usuario", "{0} user", "{0} användare"),
    ("usr.count.many", "{0} usuarios", "{0} users", "{0} användare"),
    ("usr.col.user", "Usuario", "User", "Användare"),
    ("usr.col.role", "Rol", "Role", "Roll"),
    ("usr.col.status", "Estado", "Status", "Status"),
    ("usr.col.last_login", "Último acceso", "Last sign-in", "Senaste inloggning"),
    ("usr.col.created", "Creado", "Created", "Skapad"),
    ("usr.col.actions", "Acciones", "Actions", "Åtgärder"),
    ("usr.active", "Activo", "Active", "Aktiv"),
    ("usr.disabled", "Desactivado", "Disabled", "Inaktiverad"),
    ("usr.you", "Tú", "You", "Du"),
    ("usr.empty", "No hay usuarios con estos filtros.", "No users match these filters.", "Inga användare matchar filtren."),
    ("usr.edit", "Editar", "Edit", "Redigera"),
    ("usr.edit_aria", "Editar a {0}", "Edit {0}", "Redigera {0}"),
    ("usr.edit_title", "Editar usuario", "Edit user", "Redigera användare"),
    ("usr.delete", "Eliminar", "Delete", "Ta bort"),
    ("usr.delete_aria", "Eliminar a {0}", "Delete {0}", "Ta bort {0}"),
    ("usr.delete_title", "Eliminar usuario", "Delete user", "Ta bort användare"),
    ("usr.delete_text", "¿Eliminar a {0} ({1})? Esta acción no se puede deshacer.", "Delete {0} ({1})? This cannot be undone.", "Ta bort {0} ({1})? Det går inte att ångra."),
    ("usr.delete_history", "Su historial de actividad se conserva en el registro.", "Their activity history stays in the log.", "Deras aktivitetshistorik finns kvar i loggen."),
    ("usr.delete_confirm", "Sí, eliminar", "Yes, delete", "Ja, ta bort"),
    ("usr.back", "Volver a usuarios", "Back to users", "Tillbaka till användare"),
    ("usr.field.name", "Nombre", "Name", "Namn"),
    ("usr.field.email", "Correo electrónico", "Email", "E-post"),
    ("usr.field.username", "Nombre de usuario (opcional)", "Username (optional)", "Användarnamn (valfritt)"),
    ("usr.field.login", "Identificador de acceso", "Sign-in ID", "Inloggnings-ID"),
    ("usr.field.login_hint", "Puede entrar con el correo o con el nombre de usuario. Hace falta al menos uno.", "They can sign in with the email or the username. At least one is required.", "De kan logga in med e-post eller användarnamn. Minst ett krävs."),
    ("usr.field.lang", "Idioma", "Language", "Språk"),
    ("usr.field.active", "Cuenta activa", "Account active", "Kontot är aktivt"),
    ("usr.field.password", "Contraseña inicial (opcional)", "Initial password (optional)", "Första lösenord (valfritt)"),
    ("usr.field.password_hint", "Si la dejas vacía se genera una contraseña temporal segura, que se muestra una sola vez.", "If left empty, a secure temporary password is generated and shown only once.", "Lämnas det tomt skapas ett säkert tillfälligt lösenord som visas bara en gång."),
    ("usr.field.must_change", "Pedir cambio de contraseña en el primer acceso", "Require a password change at first sign-in", "Kräv lösenordsbyte vid första inloggningen"),
    ("usr.reset.title", "Restablecer contraseña", "Reset password", "Återställ lösenord"),
    ("usr.reset.text", "Genera una contraseña temporal y cierra sus sesiones. Tendrá que cambiarla al entrar.", "Generates a temporary password and signs them out everywhere. They must change it when signing in.", "Skapar ett tillfälligt lösenord och loggar ut dem överallt. De måste byta det vid inloggning."),
    ("usr.reset.button", "Restablecer contraseña", "Reset password", "Återställ lösenord"),
    ("usr.temp.title", "Contraseña temporal", "Temporary password", "Tillfälligt lösenord"),
    ("usr.temp.created", "Cuenta creada para {0}.", "Account created for {0}.", "Konto skapat för {0}."),
    ("usr.temp.reset", "Contraseña de {0} restablecida.", "Password for {0} has been reset.", "Lösenordet för {0} har återställts."),
    ("usr.temp.password", "Contraseña temporal", "Temporary password", "Tillfälligt lösenord"),
    ("usr.temp.copy", "Copiar contraseña", "Copy password", "Kopiera lösenordet"),
    ("usr.temp.once", "Guárdala ahora: no se volverá a mostrar.", "Save it now: it will not be shown again.", "Spara det nu: det visas inte igen."),
    ("usr.temp.must_change", "Tendrá que cambiarla al iniciar sesión.", "They will have to change it when signing in.", "De måste byta det vid inloggning."),
    ("usr.flash.created", "Usuario creado.", "User created.", "Användaren har skapats."),
    ("usr.flash.updated", "Cambios guardados.", "Changes saved.", "Ändringarna har sparats."),
    ("usr.flash.deleted", "Usuario eliminado.", "User deleted.", "Användaren har tagits bort."),
    ("usr.flash.password", "Contraseña restablecida.", "Password reset.", "Lösenordet har återställts."),
    ("usr.err.name", "El nombre es obligatorio (máximo 80 caracteres).", "The name is required (80 characters at most).", "Namn krävs (högst 80 tecken)."),
    ("usr.err.login_required", "Indica un correo o un nombre de usuario.", "Enter an email or a username.", "Ange en e-postadress eller ett användarnamn."),
    ("usr.err.email", "El correo electrónico no es válido.", "The email address is not valid.", "E-postadressen är ogiltig."),
    ("usr.err.username", "Nombre de usuario no válido (3–40 caracteres: letras, números, punto, guion y guion bajo).", "Invalid username (3–40 characters: letters, digits, dot, hyphen and underscore).", "Ogiltigt användarnamn (3–40 tecken: bokstäver, siffror, punkt, bindestreck och understreck)."),
    ("usr.err.dup_email", "Ya existe un usuario con ese correo.", "A user with that email already exists.", "Det finns redan en användare med den e-postadressen."),
    ("usr.err.dup_username", "Ya existe un usuario con ese nombre de usuario.", "A user with that username already exists.", "Det finns redan en användare med det användarnamnet."),
    ("usr.err.role_not_allowed", "No puedes asignar ese rol.", "You cannot assign that role.", "Du kan inte tilldela den rollen."),
    ("usr.err.own_role_status", "No puedes cambiar tu propio rol ni desactivar tu cuenta.", "You cannot change your own role or disable your own account.", "Du kan inte ändra din egen roll eller inaktivera ditt eget konto."),
    ("usr.err.last_superadmin", "Debe quedar al menos un superadmin activo.", "At least one active superadmin must remain.", "Minst en aktiv superadmin måste finnas kvar."),

    // ───── Actividad (solo superadmin) ─────
    ("act.lead", "Quién entró, qué vio y qué cambió en la plataforma. Solo el superadmin ve esta pantalla.", "Who signed in, what they viewed and what they changed. Only the superadmin sees this screen.", "Vem som loggade in, vad de tittade på och vad de ändrade. Bara superadmin ser den här sidan."),
    ("act.export", "Exportar CSV", "Export CSV", "Exportera CSV"),
    ("act.kpi.users", "Usuarios", "Users", "Användare"),
    ("act.kpi.active", "Usuarios activos (24 h)", "Active users (24 h)", "Aktiva användare (24 h)"),
    ("act.kpi.events", "Eventos (24 h)", "Events (24 h)", "Händelser (24 h)"),
    ("act.kpi.searches", "Búsquedas (24 h)", "Searches (24 h)", "Sökningar (24 h)"),
    ("act.kpi.failed", "Accesos fallidos (24 h)", "Failed sign-ins (24 h)", "Misslyckade inloggningar (24 h)"),
    ("act.by_user", "Actividad por usuario", "Activity by user", "Aktivitet per användare"),
    ("act.by_user_about", "Sobre este resumen", "About this summary", "Om den här sammanfattningen"),
    ("act.by_user_tip", "Totales desde que empezó el registro. «Empresas» cuenta empresas distintas consultadas.", "Totals since logging began. “Companies” counts distinct companies viewed.", "Summor sedan loggningen startade. ”Företag” räknar unika företag som visats."),
    ("act.col.last_seen", "Última actividad", "Last activity", "Senaste aktivitet"),
    ("act.col.logins", "Accesos", "Sign-ins", "Inloggningar"),
    ("act.col.views", "Páginas vistas", "Page views", "Sidvisningar"),
    ("act.col.searches", "Búsquedas", "Searches", "Sökningar"),
    ("act.col.companies", "Empresas", "Companies", "Företag"),
    ("act.col.detail", "Detalle", "Detail", "Detalj"),
    ("act.col.event", "Evento", "Event", "Händelse"),
    ("act.col.time", "Fecha y hora", "Time", "Tid"),
    ("act.never", "Nunca", "Never", "Aldrig"),
    ("act.see_user", "Ver su actividad", "View their activity", "Visa deras aktivitet"),
    ("act.see_user_aria", "Ver la actividad de {0}", "View activity of {0}", "Visa aktiviteten för {0}"),
    ("act.all_users", "Todos los usuarios", "All users", "Alla användare"),
    ("act.all_events", "Todos los eventos", "All events", "Alla händelser"),
    ("act.search", "Buscar en ruta o detalle…", "Search path or detail…", "Sök i sökväg eller detalj…"),
    ("act.from", "Desde", "From", "Från"),
    ("act.to", "Hasta", "To", "Till"),
    ("act.count", "{0} eventos", "{0} events", "{0} händelser"),
    ("act.empty", "No hay eventos con estos filtros.", "No events match these filters.", "Inga händelser matchar filtren."),
    ("act.pager", "Paginación", "Pagination", "Sidnavigering"),
    ("act.prev", "Anterior", "Previous", "Föregående"),
    ("act.next", "Siguiente", "Next", "Nästa"),
    ("act.page_of", "Página {0} de {1}", "Page {0} of {1}", "Sida {0} av {1}"),
    ("act.privacy", "Se registran accesos (también los fallidos), páginas vistas, búsquedas, empresas consultadas y cambios de cuentas, con hora, IP y navegador. Las contraseñas nunca se guardan. Los registros se conservan 365 días.", "Sign-ins (including failed ones), page views, searches, companies viewed and account changes are recorded with time, IP and browser. Passwords are never stored. Records are kept for 365 days.", "Inloggningar (även misslyckade), sidvisningar, sökningar, visade företag och kontoändringar loggas med tid, IP och webbläsare. Lösenord sparas aldrig. Loggen sparas i 365 dagar."),
    ("act.event.login_ok", "Acceso correcto", "Signed in", "Inloggning"),
    ("act.event.login_fail", "Acceso fallido", "Failed sign-in", "Misslyckad inloggning"),
    ("act.event.login_blocked", "Acceso bloqueado", "Sign-in blocked", "Inloggning blockerad"),
    ("act.event.logout", "Cierre de sesión", "Signed out", "Utloggning"),
    ("act.event.view", "Página vista", "Page view", "Sidvisning"),
    ("act.event.search", "Búsqueda", "Search", "Sökning"),
    ("act.event.company_view", "Empresa consultada", "Company viewed", "Företag visat"),
    ("act.event.access_denied", "Acceso denegado", "Access denied", "Åtkomst nekad"),
    ("act.event.lang_change", "Cambio de idioma", "Language changed", "Språk ändrat"),
    ("act.event.user_create", "Usuario creado", "User created", "Användare skapad"),
    ("act.event.user_update", "Usuario modificado", "User updated", "Användare ändrad"),
    ("act.event.user_delete", "Usuario eliminado", "User deleted", "Användare borttagen"),
    ("act.event.password_reset", "Contraseña restablecida", "Password reset", "Lösenord återställt"),
    ("act.event.password_change", "Contraseña cambiada", "Password changed", "Lösenord ändrat"),
    ("act.event.password_change_fail", "Cambio de contraseña fallido", "Password change failed", "Lösenordsbyte misslyckades"),
    ("act.event.profile_update", "Perfil actualizado", "Profile updated", "Profil uppdaterad"),
    ("act.event.export", "Exportación", "Export", "Export"),

    // ───── Búsqueda ─────
    ("sok.lead", "Busca empresas suecas por nombre, ciudad o número de organización. Las empresas de la lista son datos de", "Search Swedish companies by name, city or organisation number. The companies in the list are", "Sök svenska företag på namn, ort eller organisationsnummer. Företagen i listan är"),
    ("sok.lead_b", "y no existen en realidad. Un número de organización válido se consulta en Bolagsverket (datos reales).", "data and do not really exist. A valid organisation number is looked up at Bolagsverket (real data).", "och finns inte på riktigt. Ett giltigt organisationsnummer slås upp hos Bolagsverket (verkliga data)."),
    ("sok.label", "Buscar empresa", "Search company", "Sök företag"),
    ("sok.placeholder", "Nombre, ciudad o nº de organización", "Name, city or org. number", "Namn, ort eller org.nr"),
    ("sok.submit", "Buscar", "Search", "Sök"),
    ("sok.clear", "Limpiar", "Clear", "Rensa"),
    ("sok.hint_a", "Pulsa", "Press", "Tryck"),
    ("sok.hint_b", "para ir al buscador desde cualquier lugar.", "to jump to the search box from anywhere.", "för att hoppa till sökrutan var som helst."),
    ("sok.caption", "Resultados de la búsqueda de empresas", "Company search results", "Sökresultat för företag"),
    ("sok.count.one_company", "{0} empresa", "{0} company", "{0} företag"),
    ("sok.count.companies", "{0} empresas", "{0} companies", "{0} företag"),
    ("sok.count.hit", "{0} resultado para «{1}»", "{0} result for “{1}”", "{0} träff för ”{1}”"),
    ("sok.count.hits", "{0} resultados para «{1}»", "{0} results for “{1}”", "{0} träffar för ”{1}”"),
    ("sok.col.company", "Empresa", "Company", "Företag"),
    ("sok.col.city", "Ciudad", "City", "Ort"),
    ("sok.col.revenue", "Facturación ({0})", "Revenue ({0})", "Omsättning ({0})"),
    ("sok.col.result", "Resultado ({0})", "Result ({0})", "Resultat ({0})"),
    ("sok.col.risk", "Riesgo", "Risk", "Risk"),
    ("sok.sort.company", "empresa", "company", "företag"),
    ("sok.sort.revenue", "facturación", "revenue", "omsättning"),
    ("sok.sort.result", "resultado", "result", "resultat"),
    ("sok.sort.asc", "ascendente", "ascending", "stigande"),
    ("sok.sort.desc", "descendente", "descending", "fallande"),
    ("sok.sort.tip", "Ordenar por {1} ({0})", "Sort by {1} ({0})", "Sortera efter {1} ({0})"),
    ("sok.empty.title", "Sin resultados", "No results", "Inga resultat"),
    ("sok.empty.text", "Prueba con otro nombre, ciudad o número de organización.", "Try another name, city or organisation number.", "Prova ett annat namn, en annan ort eller ett annat organisationsnummer."),
    ("sok.empty.all", "Ver todas", "Show all", "Visa alla"),
    ("sok.note.example", "Datos de demostración: no son empresas reales.", "Demo data: these are not real companies.", "Demodata: det är inte verkliga företag."),
    ("sok.note.live", "Resultado real de Bolagsverket. La API gratuita solo permite buscar por número de organización, no por nombre.", "Real result from Bolagsverket. The free API only supports lookup by organisation number, not by name.", "Verkligt resultat från Bolagsverket. Det gratis API:et stöder bara sökning på organisationsnummer, inte namn."),

    // ───── Ficha de empresa ─────
    ("co.back", "Volver a la búsqueda", "Back to search", "Tillbaka till sökningen"),
    ("co.org_nr", "Nº de organización", "Org. number", "Org.nr"),
    ("co.copy_org", "Copiar número de organización", "Copy organisation number", "Kopiera organisationsnummer"),
    ("co.copy_org_aria", "Copiar el número de organización {0}", "Copy organisation number {0}", "Kopiera organisationsnummer {0}"),
    ("co.views", "Vistas de la empresa", "Company views", "Företagsvyer"),
    ("tab.overview", "Visión general", "Overview", "Översikt"),
    ("tab.financials", "Finanzas", "Financials", "Ekonomi"),
    ("tab.people", "Personas", "People", "Personer"),
    ("tab.summary", "Resumen IA", "AI summary", "AI-sammanfattning"),
    ("status.active", "Activa", "Active", "Aktivt"),
    ("risk.low", "Riesgo bajo", "Low risk", "Låg risk"),
    ("risk.watch", "En observación", "Watch", "Bevaka"),
    ("risk.high", "Riesgo alto", "High risk", "Hög risk"),
    ("legal.ab", "Sociedad anónima (AB)", "Limited company (AB)", "Aktiebolag (AB)"),
    ("sni.52290", "Otras actividades de apoyo al transporte", "Other transportation support activities", "Andra stödtjänster till transport"),
    ("sni.41200", "Construcción de edificios", "Construction of buildings", "Byggande av bostäder och andra byggnader"),
    ("sni.47290", "Comercio minorista de alimentos", "Retail sale of food", "Specialiserad butikshandel med livsmedel"),
    ("sign.two", "Dos personas en conjunto", "Two people jointly", "Två i förening"),
    ("sign.alone", "Cada una por separado", "Each person alone", "Var för sig"),
    ("role.ceo", "Director general (VD)", "CEO (VD)", "VD"),
    ("role.chair", "Presidente de la junta", "Chair of the board", "Styrelseordförande"),
    ("role.member", "Miembro de la junta", "Board member", "Styrelseledamot"),
    ("term.margin", "Margen neto", "Net margin", "Nettomarginal"),
    ("term.solidity", "Solidez", "Equity ratio", "Soliditet"),
    ("term.liquidity", "Liquidez", "Quick ratio", "Kassalikviditet"),
    ("tip.org_nr", "Número de 10 dígitos que identifica a la empresa en el registro sueco.", "The 10-digit number that identifies the company in the Swedish register.", "Det tiosiffriga nummer som identifierar företaget i det svenska registret."),
    ("tip.revenue", "Ventas netas del último ejercicio (omsättning).", "Net sales for the latest financial year (omsättning).", "Nettoomsättning för senaste räkenskapsåret."),
    ("tip.result", "Resultado del ejercicio después de impuestos.", "Profit or loss for the year after tax.", "Årets resultat efter skatt."),
    ("tip.margin", "Resultado dividido por la facturación: cuánto queda de cada corona vendida.", "Result divided by revenue: how much is left of each krona sold.", "Resultat delat med omsättning: hur mycket som blir kvar av varje såld krona."),
    ("tip.solidity", "Patrimonio neto dividido por los activos totales: qué parte se financia con capital propio.", "Equity divided by total assets: the share financed by the owners' own capital.", "Eget kapital delat med summa tillgångar: hur stor del som finansieras med eget kapital."),
    ("tip.solidity.bench", "Patrimonio neto sobre activos totales (soliditet). Más alto es más sólido.", "Equity over total assets (soliditet). Higher is sturdier.", "Eget kapital i förhållande till summa tillgångar (soliditet). Högre är stabilare."),
    ("tip.liquidity", "Capacidad de pagar las deudas a corto plazo con activos líquidos. Más de 100 % es una posición cómoda.", "Ability to pay short-term debts with liquid assets. Above 100% is comfortable.", "Förmåga att betala kortfristiga skulder med likvida tillgångar. Över 100 % är en bekväm nivå."),
    ("tip.employees", "Intervalo de empleados según la clasificación por tamaño de SCB.", "Employee range using Statistics Sweden's size classes.", "Intervall för antal anställda enligt SCB:s storleksklasser."),
    ("tip.sni", "Clasificación sueca de actividades económicas (SNI 2007), basada en la europea NACE.", "Swedish standard industrial classification (SNI 2007), based on the European NACE.", "Svensk näringsgrensindelning (SNI 2007), baserad på den europeiska NACE."),
    ("kpi.revenue", "Facturación", "Revenue", "Omsättning"),
    ("kpi.result", "Resultado", "Result", "Resultat"),
    ("kpi.employees", "Empleados", "Employees", "Anställda"),
    ("kpi.scb_interval", "Intervalo según SCB", "Range per Statistics Sweden", "Intervall enligt SCB"),
    ("kpi.equity_is", "Patrimonio neto {0}", "Equity {0}", "Eget kapital {0}"),
    ("kpi.vs_year", "{0}\u{00A0}% frente a {1}", "{0}% vs {1}", "{0}\u{00A0}% mot {1}"),
    ("kpi.increase", "Aumento: ", "Increase: ", "Ökning: "),
    ("kpi.decrease", "Disminución: ", "Decrease: ", "Minskning: "),
    ("ov.revenue_title", "Facturación ({0})", "Revenue ({0})", "Omsättning ({0})"),
    ("ov.revenue_caption", "Facturación por año, en {0}", "Revenue by year, in {0}", "Omsättning per år, i {0}"),
    ("ov.col.year", "Año", "Year", "År"),
    ("ov.about_chart", "Sobre el gráfico", "About the chart", "Om diagrammet"),
    ("ov.chart_tip", "Facturación de los últimos años en miles de coronas suecas.", "Revenue over the latest years in thousands of Swedish kronor.", "Omsättning de senaste åren i tusentals svenska kronor."),
    ("ov.legend.past", "Años anteriores", "Earlier years", "Tidigare år"),
    ("ov.legend.latest", "Último año", "Latest year", "Senaste året"),
    ("ov.legend.values_in", "Valores sobre las barras en {0}", "Values above the bars in {0}", "Värden ovanför staplarna i {0}"),
    ("ov.bench_title", "Comparación con el sector", "Sector comparison", "Branschjämförelse"),
    ("ov.about_bench", "Sobre la comparación con el sector", "About the sector comparison", "Om branschjämförelsen"),
    ("ov.bench_tip", "La mediana del sector viene de SCB (Estadísticas de Suecia) para empresas del mismo SNI y tamaño.", "The sector median comes from Statistics Sweden (SCB) for companies with the same SNI and size.", "Branschmedianen kommer från SCB för företag med samma SNI och storlek."),
    ("ov.loading_bench", "Cargando la comparación con el sector…", "Loading the sector comparison…", "Läser in branschjämförelsen…"),
    ("ov.bench_error", "No se pudo cargar la comparación con el sector.", "The sector comparison could not be loaded.", "Branschjämförelsen kunde inte läsas in."),
    ("ov.bench_failed", "No se pudo consultar SCB ahora. Se muestran valores de ejemplo.", "SCB could not be reached right now. Showing example values.", "SCB kunde inte nås just nu. Visar exempelvärden."),
    ("ov.bench_nojs", "Activa JavaScript para cargar las medianas reales de SCB. Se muestran valores de ejemplo.", "Enable JavaScript to load the real SCB medians. Showing example values.", "Aktivera JavaScript för att läsa in SCB:s verkliga medianer. Visar exempelvärden."),
    ("ov.signals", "Señales", "Signals", "Signaler"),
    ("ov.activity", "Actividad (SNI)", "Activity (SNI)", "Verksamhet (SNI)"),
    ("bench.aria", "{0}: empresa {1}, mediana del sector {2}", "{0}: company {1}, sector median {2}", "{0}: företaget {1}, branschmedian {2}"),
    ("bench.tip", "{0}: {1} frente a la mediana del sector de {2}, {4} puntos {3}.", "{0}: {1} vs the sector median of {2}, {4} points {3}.", "{0}: {1} mot branschens median {2}, {4} punkter {3}."),
    ("bench.above", "por encima", "above", "över"),
    ("bench.below", "por debajo", "below", "under"),
    ("bench.median_text", "mediana {0}", "median {0}", "median {0}"),
    ("bench.legend.company", "Empresa", "Company", "Företaget"),
    ("bench.legend.median", "Mediana del sector", "Sector median", "Branschmedian"),
    ("bench.all_sizes", "todos los tamaños", "all sizes", "alla storlekar"),
    ("bench.size", "tamaño {0} empleados", "size {0} employees", "storlek {0} anställda"),
    ("bench.note.real", "Medianas del sector: SNI {0}{1}, {2}, {3} (fuente: SCB, datos reales).", "Sector medians: SNI {0}{1}, {2}, {3} (source: Statistics Sweden, real data).", "Branschmedianer: SNI {0}{1}, {2}, {3} (källa: SCB, verkliga data)."),
    ("bench.note.fallback", "No hay datos exactos para SNI {0} y {1} empleados; se usó el grupo más cercano.", "There is no exact data for SNI {0} and {1} employees; the closest group was used.", "Det finns inga exakta data för SNI {0} och {1} anställda; närmaste grupp användes."),
    ("bench.note.own", "La cifra de la empresa es de", "The company's own figure is", "Företagets egen siffra är"),
    ("bench.note.example", "Medianas del sector (SNI {0}) de", "Sector medians (SNI {0}) are", "Branschmedianer (SNI {0}) är"),
    ("fin.revenue", "Facturación", "Revenue", "Omsättning"),
    ("fin.result", "Resultado del ejercicio", "Net result", "Årets resultat"),
    ("fin.equity", "Patrimonio neto", "Equity", "Eget kapital"),
    ("fin.assets", "Activos totales", "Total assets", "Summa tillgångar"),
    ("fin.caption", "Cifras clave por año, en {0}", "Key figures by year, in {0}", "Nyckeltal per år, i {0}"),
    ("fin.source", "Las cifras financieras son de", "The financial figures are", "Siffrorna är"),
    ("fin.download", "Descargar informe", "Download report", "Ladda ner rapport"),
    ("fin.download_tip", "Disponible en una versión futura", "Available in a future version", "Kommer i en framtida version"),
    ("ppl.caption", "Personas con cargo en la empresa", "People holding a role in the company", "Personer med uppdrag i företaget"),
    ("ppl.role", "Cargo", "Role", "Roll"),
    ("ppl.name", "Nombre", "Name", "Namn"),
    ("ppl.signing", "Firma (firmateckning)", "Signatory rights (firmateckning)", "Firmateckning"),
    ("ppl.note", "Los nombres de las personas son ficticios y de", "The names are fictitious and are", "Namnen är fiktiva och är"),
    ("sum.title", "Resumen", "Summary", "Sammanfattning"),
    ("sum.note", "Texto redactado con una plantilla, sin IA real, a partir de datos de", "Text written from a template, without real AI, based on", "Text skriven med en mall, utan riktig AI, utifrån"),
    ("summary.good", "Evolución sólida. La facturación ha crecido cada año hasta {0} mil SEK y la solidez es del {1} %, por encima de la mediana del sector. No hay señales de alerta en los datos.", "Strong performance. Revenue has grown every year, to {0} kSEK, and the equity ratio is {1}%, above the sector median. No warning signs in the data.", "Stark utveckling. Omsättningen har vuxit varje år, till {0} tkr, och soliditeten är {1} %, över branschens median. Inga varningssignaler i underlaget."),
    ("summary.warn", "Cuadro mixto. La facturación sigue creciendo ({0} % el último año), pero el margen neto es de solo {1} %, por debajo de la mediana del sector. Conviene vigilar los costes.", "Mixed picture. Revenue is still growing ({0}% last year), but the net margin is only {1}%, below the sector median. Worth keeping an eye on costs.", "Blandad bild. Omsättningen växer fortfarande ({0} % senaste året), men nettomarginalen är bara {1} %, under branschens median. Värt att hålla koll på kostnaderna."),
    ("summary.bad", "Atención. La empresa ha tenido pérdidas dos años seguidos ({0} y {1} mil SEK) y la solidez es de solo {2} %, muy por debajo de la mediana del sector. Riesgo alto: conviene revisar el último informe y los planes de la junta.", "Warning. The company has posted losses two years in a row ({0} and {1} kSEK) and the equity ratio is only {2}%, well below the sector median. High risk: review the latest report and the board's plans.", "Varning. Företaget har gått med förlust två år i rad ({0} och {1} tkr) och soliditeten är bara {2} %, långt under branschens median. Hög risk: granska senaste rapporten och styrelsens planer."),
    ("sev.good", "Correcto: ", "OK: ", "Bra: "),
    ("sev.warn", "Atención: ", "Warning: ", "Varning: "),
    ("sev.bad", "Crítico: ", "Critical: ", "Kritiskt: "),
    ("alert.report_filed", "Informe anual presentado a tiempo", "Annual report filed on time", "Årsredovisningen inlämnad i tid"),
    ("alert.board_change", "Cambio reciente en la junta directiva", "Recent change on the board", "Ny förändring i styrelsen"),
    ("alert.loss_two_years", "Pérdidas dos años seguidos", "Losses two years in a row", "Förlust två år i rad"),
    ("alert.equity_below_half", "El patrimonio neto es inferior a la mitad del capital social (riesgo de «kontrollbalansräkning»)", "Equity is below half of the share capital (risk of a “kontrollbalansräkning”)", "Eget kapital understiger hälften av aktiekapitalet (risk för kontrollbalansräkning)"),
    ("alert.new_address", "Cambio de domicilio registrado recientemente", "Registered address changed recently", "Ny adress registrerad nyligen"),
    ("alert.margin_below_median", "Margen por debajo de la mediana del sector", "Margin below the sector median", "Marginal under branschens median"),
    ("alert.no_remarks", "Sin anotaciones en el registro", "No remarks in the register", "Inga anmärkningar i registret"),

    // ───── Ficha real (Bolagsverket) ─────
    ("live.facts", "Datos del registro", "Register details", "Registeruppgifter"),
    ("live.address", "Dirección", "Address", "Adress"),
    ("live.registered", "Registrada", "Registered", "Registrerad"),
    ("live.sni", "Código SNI", "SNI code", "SNI-kod"),
    ("live.activity", "Actividad", "Activity", "Verksamhet"),
    ("live.inactive", "Inactiva", "Inactive", "Inaktivt"),
    ("live.deregistered", "Dada de baja el {0}", "Deregistered {0}", "Avregistrerat {0}"),
    ("live.swedish_note", "Las descripciones y las formas jurídicas vienen del registro y se muestran en sueco.", "Descriptions and legal forms come from the register and are shown in Swedish.", "Beskrivningar och företagsformer kommer från registret."),
    ("live.financials", "Cuentas anuales", "Annual accounts", "Årsredovisning"),
    ("live.about_financials", "Sobre las cifras financieras", "About the financial figures", "Om de finansiella siffrorna"),
    ("live.financials_tip", "Cifras reales extraídas de los informes anuales digitales (iXBRL) que la empresa presentó en Bolagsverket.", "Real figures read from the digital annual reports (iXBRL) the company filed with Bolagsverket.", "Verkliga siffror från de digitala årsredovisningar (iXBRL) som företaget lämnat till Bolagsverket."),
    ("live.loading", "Cargando las cuentas anuales…", "Loading the annual accounts…", "Läser in årsredovisningen…"),
    ("live.error", "No se pudieron cargar las cuentas anuales. Recarga la página para reintentarlo.", "The annual accounts could not be loaded. Reload the page to retry.", "Årsredovisningen kunde inte läsas in. Ladda om sidan för att försöka igen."),
    ("live.source", "Fuente: Bolagsverket (API gratuito de datos valiosos). Datos reales.", "Source: Bolagsverket (free high-value datasets API). Real data.", "Källa: Bolagsverket (gratis API för värdefulla datamängder). Verkliga data."),
    ("live.err.title", "Registro no disponible", "Register unavailable", "Registret är inte tillgängligt"),
    ("live.err.text", "No pudimos consultar Bolagsverket en este momento. Inténtalo de nuevo en un minuto.", "We could not reach Bolagsverket right now. Please try again in a minute.", "Vi kunde inte nå Bolagsverket just nu. Försök igen om en minut."),
    ("bok.none", "Esta empresa no ha presentado cuentas anuales digitales en Bolagsverket.", "This company has not filed digital annual accounts with Bolagsverket.", "Företaget har inte lämnat in någon digital årsredovisning till Bolagsverket."),
    ("bok.none_note", "Sin cuentas digitales no se pueden mostrar cifras reales.", "Without digital accounts no real figures can be shown.", "Utan digital årsredovisning kan inga verkliga siffror visas."),
    ("bok.no_revenue", "Esta empresa no declara facturación (omsättning) en sus cuentas digitales.", "This company does not report revenue (omsättning) in its digital accounts.", "Företaget redovisar ingen omsättning i sin digitala årsredovisning."),
    ("bok.revenue_year", "Facturación {0}", "Revenue {0}", "Omsättning {0}"),
    ("bok.source", "Fuente: cuentas anuales digitales (iXBRL) presentadas en Bolagsverket; último ejercicio cerrado el {0}. Cifras reales, en miles de coronas.", "Source: digital annual accounts (iXBRL) filed with Bolagsverket; latest financial year ended {0}. Real figures, in thousands of kronor.", "Källa: digitala årsredovisningar (iXBRL) inlämnade till Bolagsverket; senaste räkenskapsår slutade {0}. Verkliga siffror, i tusentals kronor."),

    // ───── Gráficos ─────
    ("chart.rev.title", "Facturación por año ({0})", "Revenue by year ({0})", "Omsättning per år ({0})"),
    ("chart.rev.tip", "{0}: {1} {2}", "{0}: {1} {2}", "{0}: {1} {2}"),
    ("chart.rev.tip_change", "{0}: {1} {2} ({3}{4}\u{00A0}% frente a {5})", "{0}: {1} {2} ({3}{4}% vs {5})", "{0}: {1} {2} ({3}{4}\u{00A0}% mot {5})"),
    ("chart.show_table", "Ver como tabla", "Show as table", "Visa som tabell"),
    ("chart.scroll_hint", "Desliza horizontalmente para ver todas las semanas.", "Scroll sideways to see all weeks.", "Bläddra i sidled för att se alla veckor."),
    ("chart.week_n", "Semana {0}", "Week {0}", "Vecka {0}"),
    ("chart.week_short", "S{0}", "W{0}", "v{0}"),
    ("chart.cash.title", "Caja proyectada por semana ({0})", "Projected cash by week ({0})", "Beräknad kassa per vecka ({0})"),
    ("chart.cash.desc", "Gráfico de barras de la caja proyectada semana a semana.", "Bar chart of projected cash week by week.", "Stapeldiagram över beräknad kassa vecka för vecka."),
    ("chart.cash.bar_tip", "Semana {0}: caja {1} {5}; entradas {2}, salidas {3}, neto {4} {5}.", "Week {0}: cash {1} {5}; inflows {2}, outflows {3}, net {4} {5}.", "Vecka {0}: kassa {1} {5}; inbetalningar {2}, utbetalningar {3}, netto {4} {5}."),
    ("chart.cash.below_suffix", " Por debajo del límite de riesgo.", " Below the risk limit.", " Under riskgränsen."),
    ("chart.cash.limit_label", "Límite {0}", "Limit {0}", "Gräns {0}"),
    ("chart.cash.limit_aria", "Límite de riesgo: {0} {1}", "Risk limit: {0} {1}", "Riskgräns: {0} {1}"),
    ("chart.cash.limit_tip", "Por debajo de {0} {1} la caja se considera en riesgo.", "Below {0} {1} the cash position is considered at risk.", "Under {0} {1} anses kassan vara i riskzonen."),
    ("chart.cash.limit_legend", "Límite de riesgo ({0} {1})", "Risk limit ({0} {1})", "Riskgräns ({0} {1})"),
    ("chart.cash.legend.cash", "Saldo de caja", "Cash balance", "Kassasaldo"),
    ("chart.cash.legend.below", "Por debajo del límite", "Below the limit", "Under gränsen"),
    ("chart.cash.caption_a", "El saldo más bajo es", "The lowest balance is", "Lägsta saldot är"),
    ("chart.cash.caption_b", "en la semana {0}.", "in week {0}.", "i vecka {0}."),
    ("chart.cash.table_caption", "Caja proyectada por semana, en {0}", "Projected cash by week, in {0}", "Beräknad kassa per vecka, i {0}"),
    ("chart.cash.col.week", "Semana", "Week", "Vecka"),
    ("chart.cash.col.in", "Entradas", "Inflows", "Inbetalningar"),
    ("chart.cash.col.out", "Salidas", "Outflows", "Utbetalningar"),
    ("chart.cash.col.cash", "Caja", "Cash", "Kassa"),

    // ───── Otras pantallas ─────
    ("watch.note", "Alertas de demostración. Más adelante podrás elegir qué empresas vigilar.", "Demo alerts. Later you will be able to choose which companies to watch.", "Demobevakning. Senare kan du välja vilka företag som ska bevakas."),
    ("watch.loss_registered", "Pérdida registrada en el último informe", "Loss recorded in the latest report", "Förlust redovisad i senaste rapporten"),
    ("watch.address_registered", "Nueva dirección registrada", "New address registered", "Ny adress registrerad"),
    ("watch.report_available", "Nuevo informe anual disponible", "New annual report available", "Ny årsredovisning tillgänglig"),
    ("when.today", "hoy", "today", "idag"),
    ("when.three_days", "hace 3 días", "3 days ago", "för 3 dagar sedan"),
    ("when.one_week", "hace 1 semana", "1 week ago", "för 1 vecka sedan"),
    ("liq.title", "Previsión de liquidez", "Liquidity forecast", "Likviditetsprognos"),
    ("liq.card_title", "Caja proyectada ({0})", "Projected cash ({0})", "Beräknad kassa ({0})"),
    ("liq.chart_tip", "Saldo inicial más las entradas y salidas semanales previstas.", "Opening balance plus the expected weekly inflows and outflows.", "Ingående saldo plus förväntade inbetalningar och utbetalningar per vecka."),
    ("liq.alert", "En algunas semanas la caja proyectada cae por debajo del límite de riesgo. Conviene adelantar cobros o aplazar pagos.", "In some weeks projected cash falls below the risk limit. Consider collecting earlier or postponing payments.", "Under vissa veckor sjunker den beräknade kassan under riskgränsen. Överväg att driva in tidigare eller skjuta upp betalningar."),
    ("liq.note", "Proyección de demostración con datos ficticios.", "Demo projection using fictitious data.", "Demoprognos med fiktiva data."),
    ("sie.title", "Importar contabilidad (SIE)", "Import accounts (SIE)", "Importera bokföring (SIE)"),
    ("sie.drop", "Arrastra aquí un archivo SIE", "Drop a SIE file here", "Släpp en SIE-fil här"),
    ("sie.formats", "Formatos .se, .si y .sie", "Formats .se, .si and .sie", "Format .se, .si och .sie"),
    ("sie.choose", "Elegir archivo", "Choose file", "Välj fil"),
    ("sie.inactive", "La importación todavía no está activa.", "Import is not active yet.", "Importen är inte aktiv ännu."),
    ("sie.preview", "Vista previa", "Preview", "Förhandsgranskning"),
    ("sie.caption", "Vista previa de cuentas SIE", "SIE account preview", "Förhandsgranskning av SIE-konton"),
    ("sie.col.account", "Cuenta", "Account", "Konto"),
    ("sie.col.name", "Nombre", "Name", "Namn"),
    ("sie.col.balance", "Saldo (SEK)", "Balance (SEK)", "Saldo (SEK)"),
    ("sie.note", "Vista previa con cuentas ficticias.", "Preview using fictitious accounts.", "Förhandsgranskning med fiktiva konton."),
    ("acct.bank", "Banco", "Bank", "Företagskonto"),
    ("acct.receivables", "Cuentas por cobrar", "Accounts receivable", "Kundfordringar"),
    ("acct.payables", "Cuentas por pagar", "Accounts payable", "Leverantörsskulder"),
    ("acct.vat", "IVA", "VAT", "Moms"),
    ("inv.title", "Facturas", "Invoices", "Fakturor"),
    ("inv.overdue", "Vencidas", "Overdue", "Förfallna"),
    ("inv.unpaid", "Pendientes de pago", "Unpaid", "Obetalda"),
    ("inv.paid", "Pagadas", "Paid", "Betalda"),
    ("inv.col.no", "Nº", "No.", "Nr"),
    ("inv.col.customer", "Cliente", "Customer", "Kund"),
    ("inv.col.amount", "Importe ({0})", "Amount ({0})", "Belopp ({0})"),
    ("inv.col.due", "Vencimiento", "Due date", "Förfallodatum"),
    ("inv.col.status", "Estado", "Status", "Status"),
    ("inv.note", "Facturas de demostración; la conexión con tu sistema de facturación llegará más adelante.", "Demo invoices; the link to your invoicing system will come later.", "Demofakturor; kopplingen till ditt faktureringssystem kommer senare."),

    // ───── Búsqueda por nombre en el registro ─────
    ("sok.note.registry", "Resultados del registro de empresas de Bolagsverket (datos reales, actualizados cada semana). Aquí solo se ven nombre, forma jurídica y estado; abre la empresa para ver su ficha.", "Results from Bolagsverket's company register (real data, updated weekly). Only name, legal form and status are shown here; open the company for its profile.", "Resultat från Bolagsverkets företagsregister (verkliga data, uppdateras varje vecka). Här visas bara namn, företagsform och status; öppna företaget för att se dess profil."),
    ("sok.registry_more", "Se muestran los primeros {0} resultados. Escribe más del nombre para acotar la búsqueda.", "Showing the first {0} results. Type more of the name to narrow the search.", "Visar de första {0} träffarna. Skriv mer av namnet för att begränsa sökningen."),
    ("form.ab", "Sociedad anónima (AB)", "Limited company (AB)", "Aktiebolag"),
    ("form.bab", "Banco (sociedad anónima)", "Bank limited company", "Bankaktiebolag"),
    ("form.bf", "Asociación de vivienda", "Housing association", "Bostadsförening"),
    ("form.bfl", "Sucursal de banco extranjero", "Foreign bank branch", "Utländsk banks filial"),
    ("form.brf", "Cooperativa de vivienda (BRF)", "Tenant-owner association (BRF)", "Bostadsrättsförening"),
    ("form.e", "Empresa individual", "Sole proprietorship", "Enskild näringsverksamhet"),
    ("form.eb", "Sociedad simple", "Simple partnership", "Enkelt bolag"),
    ("form.ek", "Cooperativa económica", "Economic association", "Ekonomisk förening"),
    ("form.fab", "Aseguradora (sociedad anónima)", "Insurance limited company", "Försäkringsaktiebolag"),
    ("form.fl", "Sucursal extranjera", "Foreign branch", "Utländsk filial"),
    ("form.hb", "Sociedad colectiva (HB)", "General partnership (HB)", "Handelsbolag"),
    ("form.i", "Asociación sin ánimo de lucro", "Non-profit association", "Ideell förening"),
    ("form.kb", "Sociedad comanditaria (KB)", "Limited partnership (KB)", "Kommanditbolag"),
    ("form.khf", "Cooperativa de alquiler", "Rental cooperative", "Kooperativ hyresrättsförening"),
    ("form.ofb", "Aseguradora mutua", "Mutual insurer", "Ömsesidigt försäkringsbolag"),
    ("form.s", "Fundación", "Foundation", "Stiftelse"),
    ("form.sb", "Caja de ahorros", "Savings bank", "Sparbank"),
    ("form.se", "Sociedad europea (SE)", "European company (SE)", "Europabolag"),
    ("form.sce", "Cooperativa europea", "European cooperative", "Europakooperativ"),
];
